#!/usr/bin/env bash
# deploy/oracle/setup-vm.sh
# Run ON the Oracle VM after SSH in as ubuntu/opc.
# Tested on Oracle Linux 8 (arm64) and Ubuntu 22.04 (arm64, Ampere A1).
#
# Usage:
#   scp deploy/oracle/{setup-vm.sh,docker-compose.yml} ubuntu@<VM_IP>:~/
#   ssh ubuntu@<VM_IP>
#   REDIS_PASSWORD=<strong-secret> bash setup-vm.sh
#
# Required env vars (export before running or pass inline):
#   REDIS_PASSWORD  — Redis AUTH password (mandatory, no default)
#
# Optional:
#   BACKUP_API_IMAGE — Docker image for the Rhea backup API
#                      default: ghcr.io/rhea/rhead:latest (update to your registry)
#   ENABLE_MONITORING — set to "1" to also start Prometheus + Grafana

set -euo pipefail

###############################################################################
# 0. Validate inputs
###############################################################################
if [[ -z "${REDIS_PASSWORD:-}" ]]; then
  echo "ERROR: REDIS_PASSWORD env var is required." >&2
  echo "Usage: REDIS_PASSWORD=<secret> bash setup-vm.sh" >&2
  exit 1
fi

BACKUP_API_IMAGE="${BACKUP_API_IMAGE:-ghcr.io/rhea/rhead:latest}"
ENABLE_MONITORING="${ENABLE_MONITORING:-0}"
COMPOSE_FILE="$HOME/docker-compose.yml"
ENV_FILE="$HOME/.env.rhea"

echo "==> Rhea Oracle VM Setup starting..."
echo "    Redis password length: ${#REDIS_PASSWORD} chars"
echo "    Backup API image:      $BACKUP_API_IMAGE"
echo "    Monitoring enabled:    $ENABLE_MONITORING"

###############################################################################
# 1. Detect OS and install Docker
###############################################################################
detect_os() {
  if [[ -f /etc/oracle-release ]]; then
    echo "oracle"
  elif [[ -f /etc/lsb-release ]] && grep -q Ubuntu /etc/lsb-release; then
    echo "ubuntu"
  else
    echo "unknown"
  fi
}

OS=$(detect_os)
echo "==> Detected OS: $OS"

install_docker_ubuntu() {
  apt-get update -qq
  apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
}

install_docker_oracle() {
  dnf config-manager --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
  dnf install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
}

if command -v docker &>/dev/null; then
  echo "==> Docker already installed: $(docker --version)"
else
  echo "==> Installing Docker..."
  case "$OS" in
    ubuntu) install_docker_ubuntu ;;
    oracle) install_docker_oracle ;;
    *)
      echo "ERROR: Unsupported OS. Install Docker manually then re-run." >&2
      exit 1
      ;;
  esac
fi

# Enable + start Docker
systemctl enable --now docker
# Add current user to docker group (takes effect on next login; sudo used below)
usermod -aG docker "${USER:-ubuntu}" || true
echo "==> Docker ready."

###############################################################################
# 2. Firewall rules
###############################################################################
echo "==> Configuring firewall..."

open_port() {
  local port=$1 proto=${2:-tcp}
  # Try firewalld first (Oracle Linux), then ufw (Ubuntu)
  if command -v firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --add-port="${port}/${proto}" 2>/dev/null || true
  fi
  if command -v ufw &>/dev/null; then
    ufw allow "${port}/${proto}" 2>/dev/null || true
  fi
}

# Redis
open_port 6379 tcp
# Backup FastAPI
open_port 8000 tcp
# Prometheus (only open if monitoring enabled — still harmless to punch the hole)
open_port 9090 tcp
# Grafana
open_port 3001 tcp

if command -v firewall-cmd &>/dev/null; then
  firewall-cmd --reload 2>/dev/null || true
fi
if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
  ufw reload 2>/dev/null || true
fi

echo "    NOTE: Also open these ports in Oracle Cloud Security List / NSG:"
echo "          6379/tcp, 8000/tcp, 9090/tcp, 3001/tcp"

###############################################################################
# 3. Write .env file (never put secrets in docker-compose.yml directly)
###############################################################################
echo "==> Writing $ENV_FILE ..."
cat > "$ENV_FILE" <<EOF
# Rhea Oracle VM — runtime secrets
# Generated by setup-vm.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file.

REDIS_PASSWORD=${REDIS_PASSWORD}
BACKUP_API_IMAGE=${BACKUP_API_IMAGE}
ENABLE_MONITORING=${ENABLE_MONITORING}
EOF
chmod 600 "$ENV_FILE"

###############################################################################
# 4. Persistent data directories
###############################################################################
echo "==> Creating data directories..."
mkdir -p \
  "$HOME/rhea-data/redis" \
  "$HOME/rhea-data/prometheus" \
  "$HOME/rhea-data/grafana"

# Redis needs to write AOF/RDB as the redis user (uid 999 inside container)
chown -R 999:999 "$HOME/rhea-data/redis" 2>/dev/null || \
  chmod 777 "$HOME/rhea-data/redis"

# Grafana user uid 472
chown -R 472:472 "$HOME/rhea-data/grafana" 2>/dev/null || \
  chmod 777 "$HOME/rhea-data/grafana"

###############################################################################
# 5. Custom redis.conf  (security + persistence)
###############################################################################
echo "==> Writing redis.conf ..."
mkdir -p "$HOME/rhea-data/redis-config"
cat > "$HOME/rhea-data/redis-config/redis.conf" <<EOF
# redis.conf — Rhea Oracle VM
# AOF persistence (durability)
appendonly yes
appendfsync everysec

# RDB snapshot every 5 min if >=1 key changed (belt-and-suspenders)
save 300 1
save 60 100

# Memory cap — leave headroom for OS + Backup API on 24GB VM
maxmemory 4gb
maxmemory-policy allkeys-lru

# Security
requirepass ${REDIS_PASSWORD}

# Only bind to all interfaces so Cloud Run can reach us;
# rely on firewall + AUTH for security.
bind 0.0.0.0
protected-mode no

# Disable dangerous commands
rename-command FLUSHALL  ""
rename-command FLUSHDB   ""
rename-command DEBUG     ""
rename-command CONFIG    "CONFIG_RHEA_ADMIN"
rename-command KEYS      "KEYS_RHEA_ADMIN"

# Logging
loglevel notice
logfile ""

# Persistence dir (mapped to host volume)
dir /data
EOF

###############################################################################
# 6. Pull images up-front so first start is fast
###############################################################################
echo "==> Pulling Docker images (this may take a minute)..."
docker pull redis:7-alpine &
docker pull "${BACKUP_API_IMAGE}" & 2>/dev/null || true
wait
echo "==> Images pulled."

###############################################################################
# 7. systemd service for auto-start on reboot
###############################################################################
echo "==> Installing systemd service: rhea-stack.service ..."

CURRENT_USER="${USER:-ubuntu}"
CURRENT_HOME="$HOME"

cat > /etc/systemd/system/rhea-stack.service <<EOF
[Unit]
Description=Rhea Oracle Stack (Redis + Backup API)
After=docker.service network-online.target
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
User=${CURRENT_USER}
WorkingDirectory=${CURRENT_HOME}
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/docker compose -f ${COMPOSE_FILE} --env-file ${ENV_FILE} up -d
ExecStop=/usr/bin/docker compose  -f ${COMPOSE_FILE} --env-file ${ENV_FILE} down
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable rhea-stack.service
echo "==> systemd service enabled."

###############################################################################
# 8. Start the stack now
###############################################################################
echo "==> Starting Rhea stack..."
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

echo ""
echo "==> Stack is up. Quick health check..."
sleep 3

# Test Redis auth
if docker exec rhea-redis redis-cli -a "${REDIS_PASSWORD}" PING 2>/dev/null | grep -q PONG; then
  echo "    Redis: OK (PONG received)"
else
  echo "    Redis: WARNING — PING did not return PONG. Check: docker logs rhea-redis"
fi

# Test backup API
if curl -sf http://localhost:8000/ | grep -q "ALIVE\|Rhea\|status"; then
  echo "    Backup API: OK"
else
  echo "    Backup API: not yet reachable (may still be starting)"
fi

echo ""
echo "============================================================"
echo " Setup complete."
echo " Redis:      redis://:${REDIS_PASSWORD}@<VM_PUBLIC_IP>:6379"
echo " Backup API: http://<VM_PUBLIC_IP>:8000"
if [[ "$ENABLE_MONITORING" == "1" ]]; then
  echo " Prometheus: http://<VM_PUBLIC_IP>:9090"
  echo " Grafana:    http://<VM_PUBLIC_IP>:3001  (admin / changeme)"
fi
echo ""
echo " Set in Cloud Run env:"
echo "   REDIS_URL=redis://:${REDIS_PASSWORD}@<VM_PUBLIC_IP>:6379"
echo "============================================================"
